name: 'Pipeline'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: building docker file
      run: |
        echo "building docker image"
